steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "docker/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/bank-tx-categorizer:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/bank-tx-categorizer:latest"]

images:
  - "gcr.io/$PROJECT_ID/bank-tx-categorizer:latest"
